### Numpy - Sort  [`numpy.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)   

Return a sorted copy of an array.

In [1]:
import numpy as np

In [2]:
N = np.random.randint(1,100,10)

print(N)

[42 62 32 24 85 27 34 68 13 74]


In [6]:
O = np.random.randint(1,100,24).reshape(6,4)
print(O)

[[88 35  3 39]
 [69 24 88 14]
 [99 70 42 49]
 [89 93 75 50]
 [17 99 84 64]
 [60 64 18 63]]


In [7]:
np.sort(N)

array([13, 24, 27, 32, 34, 42, 62, 68, 74, 85], dtype=int32)

In [8]:
np.sort(O)

array([[ 3, 35, 39, 88],
       [14, 24, 69, 88],
       [42, 49, 70, 99],
       [50, 75, 89, 93],
       [17, 64, 84, 99],
       [18, 60, 63, 64]], dtype=int32)

In [9]:
np.sort(O,axis=1)

array([[ 3, 35, 39, 88],
       [14, 24, 69, 88],
       [42, 49, 70, 99],
       [50, 75, 89, 93],
       [17, 64, 84, 99],
       [18, 60, 63, 64]], dtype=int32)

In [10]:
np.sort(O,axis=0)

array([[17, 24,  3, 14],
       [60, 35, 18, 39],
       [69, 64, 42, 49],
       [88, 70, 75, 50],
       [89, 93, 84, 63],
       [99, 99, 88, 64]], dtype=int32)

### NUMPY - APPEND  [`numpy.append()`](https://numpy.org/doc/stable/reference/generated/numpy.append.html)  

The numpy.append() appends values along the mentioned axis at the end of the array

In [11]:
np.append(N,100)

array([ 42,  62,  32,  24,  85,  27,  34,  68,  13,  74, 100])

In [12]:
O

array([[88, 35,  3, 39],
       [69, 24, 88, 14],
       [99, 70, 42, 49],
       [89, 93, 75, 50],
       [17, 99, 84, 64],
       [60, 64, 18, 63]], dtype=int32)

In [ ]:
np.append(O,np.array([[100,101,102,103]]),axis=0)  # axis = `0` means rows in numpy

np.append(O,np.ones((O.shape[0],1)),axis=1)      # axis = `1` means columns in numpy

array([[88., 35.,  3., 39.,  1.],
       [69., 24., 88., 14.,  1.],
       [99., 70., 42., 49.,  1.],
       [89., 93., 75., 50.,  1.],
       [17., 99., 84., 64.,  1.],
       [60., 64., 18., 63.,  1.]])

### NUMPY - CONCATENATE  [`numpy.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [16]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((a,b),axis=0)  # axis = `0` means rows in numpy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((a,b),axis=1)  # axis = `1` means columns in numpy

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### Numpy - UNIQUE  [`numpy.unique()`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [20]:
c = np.array([1,1,2,3,4,5,6,7,8,4,3,2,6,5,8,9,10])

In [21]:
c


array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  4,  3,  2,  6,  5,  8,  9, 10])

In [22]:
np.unique(c)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### NUMPY - EXPAND DIMS  [`numpy.expand_dims()`](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

### Numppy - WHERE  [`numpy.where()`](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

###  NUMPY - ARGMAX  [`numpy.argmax()`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

### NUMPY - CUMULATIVE SUM  [`numpy.cumsum()`](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

### NUMPY - PER CENTILE  [`numpy.percentile()`](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html)

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.



### NUMPY - HISTOGRAM  [`numpy.histogram()`](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html)

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.


### Numppy - CORRELATION COEFFICIENT  [`numpy.corrcoef()`](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html)

Return Pearson product-moment correlation coefficients.


### NUMPY - ISIN [`numpy.isin()`](https://numpy.org/doc/stable/reference/generated/numpy.isin.html)

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


### NUMPY - FLIP  [`numpy.flip()`](https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.


### NUMPY - PUT [`numpy.put()`](https://numpy.org/doc/stable/reference/generated/numpy.put.html)

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

### NUMPY - DELETE [`numpy.delete()`](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.


### SET FUNCTIONS IN NUMPY
    - np.union1d
    - np.intersect1d
    - np.setdiff1d
    - np.setxor1d
    - np.in1d
 These functions are used to perform set operations on arrays. They can be used to find the union, intersection, difference, and symmetric difference of two arrays, as well as to check if elements of one array are present in another array.

### NUMPY - CLIP  [`numpy.clip()`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html)

numpy.clip() function is used to Clip (limit) the values in an array.

